"use client";

import { FormEvent, useState } from "react";

export function AuthView() {
  const [step, setStep] = useState<"signin" | "twofa" | "done">("signin");
  const [error, setError] = useState("");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); if (step === "signin") setStep("twofa"); else if (step === "twofa") setStep("done"); };
  if (step === "done") return <div className="panel" style={{ maxWidth: 460, margin: "12vh auto", padding: 30, textAlign: "center" }}><div className="eyebrow">Authenticated</div><h1>Welcome back</h1><p className="muted">Your HttpOnly session is active. Continue to the governed catalog or console.</p><div style={{ display: "flex", gap: 10, justifyContent: "center" }}><a className="button primary" href="/catalog">Open catalog</a><a className="button" href="/console/api-access">Open console</a></div></div>;
  return <main className="shell" style={{ padding: 20 }}><div style={{ maxWidth: 460, margin: "10vh auto" }}><a href="/catalog" style={{ fontWeight: 800 }}>← ShennongDB</a><div className="panel" style={{ padding: 30, marginTop: 20 }}><div className="eyebrow">{step === "signin" ? "Secure sign in" : "Step-up verification"}</div><h1 style={{ marginBottom: 8 }}>{step === "signin" ? "Sign in to ShennongDB" : "Enter your 2FA code"}</h1><p className="muted">{step === "signin" ? "Use your organization account to access private resources and console controls." : "A verification code was sent to your enrolled authenticator."}</p><form onSubmit={submit} style={{ display: "grid", gap: 14, marginTop: 24 }}>{step === "signin" ? <><label>Email<input className="input" name="email" type="email" required placeholder="you@organization.org" /></label><label>Password<input className="input" name="password" type="password" required minLength={8} /></label></> : <label>Authentication code<input className="input" name="code" inputMode="numeric" pattern="[0-9]{6}" required placeholder="000000" /></label>}{error && <div style={{ color: "#a23b32" }}>{error}</div>}<button className="button primary" type="submit">{step === "signin" ? "Continue" : "Verify and sign in"}</button></form><div className="muted" style={{ marginTop: 18, fontSize: 12 }}>Session expiry and role checks are enforced server-side; this screen never stores credentials in local storage.</div></div></div></main>;
}
