"use client";

import { useEffect, useState } from "react";
import { Check, CheckCircle2, CircleSlash2, Code2, Copy, ExternalLink, FileBox, Globe2, LockKeyhole, X } from "lucide-react";
import type { ResourceRecord } from "@/lib/api/adapter";
import { CopyButton, TinyBadge } from "./app-shell";

type DrawerProps = { resource: ResourceRecord; onClose: () => void };
const tabs = ["Overview", "Schema", "Provenance", "Relations", "Access"] as const;

export function ResourceDrawer({ resource, onClose }: DrawerProps) {
  const [tab, setTab] = useState<(typeof tabs)[number]>("Overview");
  useEffect(() => { const handleKey = (event: KeyboardEvent) => event.key === "Escape" && onClose(); window.addEventListener("keydown", handleKey); return () => window.removeEventListener("keydown", handleKey); }, [onClose]);
  return <><button className="drawer-scrim" onClick={onClose} aria-label="Close resource drawer" /><aside className="resource-drawer" aria-label="Resource details"><div className="drawer-header"><div className="resource-title-wrap"><span className="resource-icon"><FileBox /></span><div><div className="drawer-title-row"><h2>{resource.name}</h2><TinyBadge tone="blue">{resource.kind}</TinyBadge></div><div className="resource-id mono">{resource.id} <Copy size={13} /></div></div></div><button className="icon-button" onClick={onClose} aria-label="Close drawer"><X /></button></div><div className="drawer-tabs">{tabs.map((item) => <button className={tab === item ? "active" : ""} key={item} onClick={() => setTab(item)}>{item}</button>)}</div><div className="drawer-content">{tab === "Overview" && <Overview resource={resource} />}{tab === "Provenance" && <Provenance resource={resource} />}{tab === "Schema" && <Schema />}{tab === "Relations" && <Relations resource={resource} />}{tab === "Access" && <Access resource={resource} />}</div>{(tab === "Overview" || tab === "Access") && <div className="auth-callout"><div><strong>Authentication</strong><p>Use an API token to programmatically access this resource.</p></div><a href="/console/api-access">View Tokens</a></div>}</aside></>;
}

function Overview({ resource }: { resource: ResourceRecord }) {
  return <><div className="detail-section"><h3>Overview</h3><div className="detail-grid"><Detail label="Description" value={resource.description} wide /><Detail label="Visibility" value={<><TinyBadge tone={resource.visibility === "Public" ? "blue" : "amber"}>{resource.visibility}</TinyBadge><span className="inline-muted">{resource.visibility === "Public" ? "Anyone can discover and read" : "Grant required"}</span></>} /><Detail label="Backend" value={<>{resource.backend} <ExternalLink size={13} /></>} /><Detail label="Storage class" value={<span className="mono soft-code">{resource.dataClass}</span>} /><Detail label="Size" value={resource.size} /><Detail label="Created" value="2024-02-18 14:22:11 UTC" /><Detail label="Updated" value="2024-05-16 10:11:52 UTC" /><Detail label="Owner" value={resource.owner} /><Detail label="Tags" value={<div className="tag-row"><TinyBadge>rna-seq</TinyBadge><TinyBadge>expression</TinyBadge><TinyBadge>toil</TinyBadge><TinyBadge>+3</TinyBadge></div>} /></div></div><Integrity resource={resource} /><ApiExample resource={resource} /><Allowed /></>;
}

function Detail({ label, value, wide = false }: { label: string; value: React.ReactNode; wide?: boolean }) { return <div className={`detail-item ${wide ? "detail-wide" : ""}`}><span>{label}</span><strong>{value}</strong></div>; }

function Integrity({ resource }: { resource: ResourceRecord }) { return <div className="detail-section"><h3>Integrity &amp; Provenance</h3><div className="detail-grid"><Detail label="SHA256" value={<span className="copy-value mono">{resource.checksum}<CopyButton value={resource.checksum} /></span>} /><Detail label="Provenance" value={<>{resource.provenance} <ExternalLink size={13} /></>} /><Detail label="Source" value={<span className="mono break-value">{resource.source}</span>} /><Detail label="Registered" value="2024-02-18 14:22:11 UTC" /></div></div>; }

function ApiExample({ resource }: { resource: ResourceRecord }) { return <div className="detail-section"><div className="section-row"><h3>API Endpoints</h3><select defaultValue="Python" aria-label="API language"><option>Python</option><option>R</option><option>cURL</option></select></div><div className="code-block"><button aria-label="Copy code"><Copy size={14} /></button><code><span className="code-key">from</span> tiledb.cloud <span className="code-key">import</span> TileDB{"\n\n"}<span className="code-key">uri</span> = <span className="code-string">&quot;tiledb://tiledb-cloud/tiles/{resource.name.toLowerCase().replaceAll(" ", "-")}.b5&quot;</span>{"\n"}<span className="code-key">with</span> tiledb.Ctx(config={"{"} <span className="code-string">&quot;vfs.s3.region&quot;</span>: <span className="code-string">&quot;us-east-1&quot;</span> {"}"}):{"\n"}    arr = tiledb.DenseArray(uri, <span className="code-string">&quot;r&quot;</span>){"\n"}    df = arr.query().to_pandas()</code></div></div>; }

function Allowed() { return <div className="detail-section"><h3>Allowed Operations</h3><div className="allowed-grid"><div><AllowedItem label="Discover" allowed /><AllowedItem label="Read" allowed /><AllowedItem label="Query (SQL)" allowed /><AllowedItem label="Download" allowed /></div><div><AllowedItem label="Write" /><AllowedItem label="Update" allowed /><AllowedItem label="Delete" /></div></div></div>; }
function AllowedItem({ label, allowed = false }: { label: string; allowed?: boolean }) { return <div className={`allowed-item ${allowed ? "allowed" : "blocked"}`}>{allowed ? <CheckCircle2 /> : <CircleSlash2 />}{label}</div>; }
function Provenance({ resource }: { resource: ResourceRecord }) { return <><div className="detail-section"><div className="section-row"><h3>Provenance lineage</h3><a href="#lineage">View full lineage <ExternalLink size={13} /></a></div><div className="lineage"><LineageNode label="S3 raw bucket · WGS reads" tone="raw" /><span>→</span><LineageNode label="Alignment (STAR)" tone="artifact" /><span>→</span><LineageNode label="Quantification" tone="artifact" /><span>→</span><LineageNode label={resource.name} tone="resource" /></div></div><Integrity resource={resource} /><div className="detail-section"><h3>Verification events</h3><div className="event-list"><div><span className="event-dot" />Checksum verified <small>2 hours ago</small></div><div><span className="event-dot" />Pipeline completed <small>2024-02-18</small></div><div><span className="event-dot" />Registered in catalog <small>2024-02-18</small></div></div></div></>; }
function LineageNode({ label, tone }: { label: string; tone: string }) { return <div className={`lineage-node ${tone}`}><span>{tone === "raw" ? "S3" : tone === "artifact" ? "ƒ" : "R"}</span><strong>{label}</strong><small>urn:sd:{label.toLowerCase().replaceAll(" ", "-")}</small></div>; }
function Schema() { return <div className="detail-section"><div className="section-row"><h3>Schema (logical)</h3><a href="#schema">View full schema <ExternalLink size={13} /></a></div><div className="schema-block"><span>1</span><code>{`{
  "type": "object",
  "properties": {
    "gene_id": { "type": "string" },
    "gene_name": { "type": "string" },
    "transcript_id": { "type": "string" },
    "sample_id": { "type": "string" },
    "value": { "type": "number" }
  }
}`}</code></div></div>; }
function Relations({ resource }: { resource: ResourceRecord }) { return <div className="detail-section"><h3>Related objects</h3><div className="relation-list"><div><GitIcon /><span><strong>{resource.name} v1</strong><small>has_artifact · canonical</small></span><ExternalLink /></div><div><GitIcon /><span><strong>TCGA clinical → survival</strong><small>derived_from · public</small></span><ExternalLink /></div><div><GitIcon /><span><strong>GENCODE gene ↔ transcript</strong><small>references · public</small></span><ExternalLink /></div></div></div>; }
function GitIcon() { return <span className="relation-icon"><Globe2 /></span>; }
function Access({ resource }: { resource: ResourceRecord }) { return <div className="detail-section"><h3>Access policy</h3><div className="policy-table"><div><strong>Principal</strong><strong>Access</strong><strong>Conditions</strong></div><div><span>Everyone</span><span>Read</span><span>—</span></div><div><span>Authenticated users</span><span>Read</span><span>—</span></div><div><span>{resource.owner}</span><span>{resource.visibility === "Public" ? "Read" : "Write"}</span><span>MFA required</span></div><div><span>data-stewards</span><span>Admin</span><span>IP allowlist</span></div></div><button className="text-button"><LockKeyhole />View full policy <ExternalLink size={13} /></button></div>; }
