"use client";

import { FormEvent, useEffect, useState } from "react";
import { KeyRound, LogOut, ShieldCheck } from "lucide-react";
import { changePassword, confirmTwoFactor, disableTwoFactor, enrollTwoFactor, getProfile, getTwoFactorStatus, listLoginHistory, listSessions, revokeSession, updateProfile, type JsonRecord } from "@/lib/api/adapter";
import { SectionHeader, TinyBadge } from "./app-shell";

type Page="profile"|"security"|"sessions"|"login-history";
export function AccountView({page}:{page:Page}){if(page==="profile")return <Profile/>;if(page==="security")return <Security/>;if(page==="sessions")return <Sessions/>;return <LoginHistory/>}

function Profile(){const[profile,setProfile]=useState<JsonRecord|null>(null);const[message,setMessage]=useState("");const[error,setError]=useState("");useEffect(()=>{void getProfile().then(setProfile).catch((reason)=>setError(reason instanceof Error?reason.message:"Profile request failed"));},[]);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=new FormData(event.currentTarget);try{const result=await updateProfile({display_name:String(form.get("display_name")),email:String(form.get("email")),locale:String(form.get("locale")),timezone:String(form.get("timezone"))});setProfile(result);setMessage("Profile saved to PostgreSQL");}catch(reason){setError(reason instanceof Error?reason.message:"Profile save failed");}}if(!profile)return <State error={error} loading="Loading profile…"/>;return <div className="console-panel"><SectionHeader title="Profile" description="Identity and preferences stored by ShennongDB."/><form className="form-grid" onSubmit={submit}><label>Display name<input name="display_name" defaultValue={text(profile.display_name)} required/></label><label>Email<input name="email" type="email" defaultValue={text(profile.email,"")} required/></label><label>Locale<input name="locale" defaultValue={text(profile.locale,"en")} required/></label><label>Timezone<input name="timezone" defaultValue={text(profile.timezone,"UTC")} required/></label>{error&&<div className="error-banner form-wide" role="alert">{error}</div>}<div className="form-wide dialog-actions"><span role="status">{message}</span><button className="primary-button">Save changes</button></div></form></div>}

function Security(){const[status,setStatus]=useState<{enabled:boolean;recovery_codes_remaining:number}|null>(null);const[enrollment,setEnrollment]=useState<{secret:string;otpauth_uri:string}|null>(null);const[codes,setCodes]=useState<string[]>([]);const[message,setMessage]=useState("");const[error,setError]=useState("");const load=()=>getTwoFactorStatus().then(setStatus);useEffect(()=>{void load().catch((reason)=>setError(reason instanceof Error?reason.message:"Security request failed"));},[]);async function password(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setError("");try{await changePassword(String(form.get("current_password")),String(form.get("new_password")));setMessage("Password updated; use the new password on your next login.");event.currentTarget.reset();}catch(reason){setError(reason instanceof Error?reason.message:"Password update failed");}}async function begin(){setError("");try{setEnrollment(await enrollTwoFactor());}catch(reason){setError(reason instanceof Error?reason.message:"Enrollment failed");}}async function confirm(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{const result=await confirmTwoFactor(String(form.get("code")));setCodes(result.recovery_codes);setEnrollment(null);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Verification failed");}}async function disable(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await disableTwoFactor(String(form.get("password")));await load();setMessage("Two-factor authentication disabled.");event.currentTarget.reset();}catch(reason){setError(reason instanceof Error?reason.message:"Disable failed");}}
return <div className="flex flex-col gap-4"><div className="console-panel"><SectionHeader title="Password" description="Changing the password updates the PBKDF2 hash in PostgreSQL."/><form className="form-grid" onSubmit={password}><label>Current password<input type="password" name="current_password" required/></label><label>New password<input type="password" name="new_password" minLength={12} required/></label><div className="form-wide dialog-actions"><button className="primary-button">Change password</button></div></form></div><div className="console-panel"><SectionHeader title="Two-factor authentication" description="TOTP enrollment and recovery codes are enforced by the Rust authentication API." action={status&&<TinyBadge tone={status.enabled?"green":"amber"}>{status.enabled?"Enabled":"Disabled"}</TinyBadge>}/>{status?.enabled?<form className="form-grid" onSubmit={disable}><p className="form-wide">{status.recovery_codes_remaining} unused recovery codes remain.</p><label>Confirm password<input type="password" name="password" required/></label><div className="form-wide"><button className="danger-button">Disable 2FA</button></div></form>:enrollment?<form className="form-grid" onSubmit={confirm}><div className="form-wide"><strong>Authenticator secret</strong><code className="code-block">{enrollment.secret}</code><p className="break-value">{enrollment.otpauth_uri}</p></div><label>Six-digit code<input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required/></label><div className="form-wide"><button className="primary-button">Verify and enable</button></div></form>:<button className="primary-button" onClick={()=>void begin()}><ShieldCheck/>Enroll authenticator</button>}{codes.length>0&&<div className="detail-section"><h3>Recovery codes — save them now</h3><div className="code-block">{codes.join("\n")}</div></div>}{error&&<div className="error-banner" role="alert">{error}</div>}<div role="status">{message}</div></div></div>}

function Sessions(){const[rows,setRows]=useState<JsonRecord[]>([]);const[error,setError]=useState("");async function load(){setRows(await listSessions())}useEffect(()=>{void load().catch((reason)=>setError(reason instanceof Error?reason.message:"Session request failed"));},[]);async function revoke(id:string){try{await revokeSession(id);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Revoke failed");}}return <div className="console-panel"><SectionHeader title="Active sessions" description="Server-side session records backed by revocable access tokens."/>{error&&<div className="error-banner" role="alert">{error}</div>}<Table columns={["User agent","IP address","Created","Last seen","Expires","Action"]} rows={rows.map((row)=>[text(row.user_agent),text(row.ip_address),text(row.created_at),text(row.last_seen_at),text(row.expires_at),"__action__"])} action={(index)=><button className="danger-button compact" onClick={()=>void revoke(text(rows[index].token_id))}><LogOut/>Revoke</button>}/></div>}

function LoginHistory(){const[rows,setRows]=useState<JsonRecord[]>([]);const[error,setError]=useState("");useEffect(()=>{void listLoginHistory().then(setRows).catch((reason)=>setError(reason instanceof Error?reason.message:"Login history request failed"));},[]);return <div className="console-panel"><SectionHeader title="Login history" description="Successful and failed authentication events recorded by the Rust API."/>{error&&<div className="error-banner" role="alert">{error}</div>}<Table columns={["Time","Result","IP address","User agent","Failure reason"]} rows={rows.map((row)=>[text(row.created_at),row.success?"Success":"Failed",text(row.ip_address),text(row.user_agent),text(row.failure_reason)])}/></div>}

function Table({columns,rows,action}:{columns:string[];rows:string[][];action?:(index:number)=>React.ReactNode}){return <div className="record-table-wrap"><table className="simple-table"><thead><tr>{columns.map((column)=><th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={`${row[0]}-${index}`}>{row.map((cell,cellIndex)=><td key={cellIndex}>{cell==="__action__"&&action?action(index):cellIndex===0?<strong>{cell}</strong>:cell==="Success"?<TinyBadge tone="green">{cell}</TinyBadge>:cell}</td>)}</tr>)}</tbody></table>{rows.length===0&&<div className="empty-state"><KeyRound/><h3>No records</h3><p>The API returned no persisted records.</p></div>}</div>}
function State({error,loading}:{error:string;loading:string}){return error?<div className="error-banner" role="alert">{error}</div>:<div className="loading-state">{loading}</div>}
function text(value:unknown,fallback="—"){return value===null||value===undefined||value===""?fallback:String(value)}
